# Generated by Django 3.2.13 on 2022-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Url', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=20)),
                ('Activate', models.BooleanField(null=True)),
            ],
        ),
    ]
