# Generated by Django 3.2.13 on 2022-04-16 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webGym', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainmenu',
            old_name='Url',
            new_name='Alias',
        ),
        migrations.RemoveField(
            model_name='mainmenu',
            name='Activate',
        ),
    ]
