# Generated by Django 3.2.13 on 2022-04-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webGym', '0002_auto_20220416_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='Position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='Alias',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mainmenu',
            name='Name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
