# Generated by Django 3.2.18 on 2023-02-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webGym', '0003_auto_20220416_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titile', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('image_src', models.CharField(max_length=255, null=True)),
                ('Position', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='main_icon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.CharField(max_length=255, null=True)),
                ('url', models.CharField(max_length=255, null=True)),
                ('titile', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('Position', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='banner_button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
                ('Position', models.IntegerField(null=True)),
                ('Slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webGym.banner')),
            ],
        ),
    ]
